Avoid spurious test suite failures due to socket removal race. When gpg-agent notices that its primary socket has been removed, it shuts down.  When it shuts down, it closes and unlinks its other sockets as well.
These rmtree invocations look like they might be getting the list of
files to delete and then unlinking them one at a time.

The result is a lot of errors like:

File "/home/dkg/src/python-gnupg/python-gnupg/gnupg.py", line 1157, in gnupg.GPG.list_keys
Failed example:
    shutil.rmtree("keys")
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest gnupg.GPG.list_keys[1]>", line 1, in <module>
        shutil.rmtree("keys")
      File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
        _rmtree_safe_fd(fd, path, onerror)
      File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
        onerror(os.unlink, fullname, sys.exc_info())
      File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
        os.unlink(name, dir_fd=topfd)
    FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'

Simply making rmtree ignore errors (as this patch does) is enough to
make the tests pass cleanly with GnuPG 2.1.18-6 and Python 3.5.3-1 on
Debian stretch (testing).